[build]
  base = "client"
  command = "yarn build"
  publish = "dist"
[[headers]]
  for = "*"
  [headers.values]
    Content-Security-Policy = "frame-ancestors 'none'"
    Referrer-Policy = "no-referrer-when-downgrade"
    X-Content-Type-Options = "nosniff"
[[headers]]
  for = "*.(css|ico|png|svg)"
  [headers.values]
    Cache-Control = "public,max-age=31536000,immutable"
[[headers]]
  for = "src.*.js"
  [headers.values]
    Cache-Control = "public,max-age=31536000,immutable"
[[redirects]]
  from = "api/*"
  status = 200
  to = "https://x2gb6pfo69.execute-api.us-east-1.amazonaws.com/prod/:splat"
[[redirects]]
  from = "*"
  status = 200
  to = "/"
